Bug:
  - '(bsc#|bug|Bug|wrong|Wrong)
Blocked:
  - '(vmware|VMWare|VMware)'
networking:
  - '(\W*((?i)cilium(?-i))\W*$|\W*((?i)envoy(?-i))\W*$|\W*((?i)istio(?-i))\W*$)'
PO/PM:
  - '(vmware|VMWare|VMware)'
v3:
  - '(v3|suse-caasp-3)'
v4:
  - '(v4|suse-caasp-4)'
AdminGuide:
  - '(caasp-admin|Admin|admin)'
DeploymentGuide:
  - '(caasp-deployment|Deployment|deployment)'
#Overhead:
EngineeringInput:
  - ('Martin-Weiss')
